### ISSUE TITLE
Assertion Error : f_numverts == 3 or 4

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#243]
@niftools/blender-nif-plugin-reviewer 
## Issue Overview

Unable to export as there is an assertion on the number of vertices
### Blender Nif Plugin Version Info

Blender Nif Plugin v2.6.0.dev4-02-04-2016
https://www.dropbox.com/s/6r7gz3m38r83x6e/blender_nif_plugin-2.6.0a0.dev4-02.04.2016.zip?dl=0
### Blender Version Info

Blender 2.77 64bit - Default installation location
### Platform information

Win 7
## Context

Attempting to export the mesh fails with the supplied messages.
It appears that there is faces without the required number of vertices
## Steps to Reproduce

 #. Export the mesh with the default settings targeting Skyrim.
## Expected Result

Mesh should be exported without error
## Actual Result

Unable to export the mesh due to the assertion check
## Possible Fix
- Check that there the assertion is correct as the mesh appears to be triangulated
- Improvement to highlight the problematic face, should think about whether or not to process all and assert at the end instead to provide the most feedback
- Improvement to use triangulation modifier
## Screenshot

N/A
## Logs and Files

[Provide logs file generated during the error as well as the blend and nif files are related to the issue]
### Info Bar Output

Traceback (most recent call last):

```
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\operators\nif_export_op.py", line 171, in execute
    return nif_export.NifExport(self, context).execute()
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\nif_export.py", line 261, in execute
    self.objecthelper.export_node(root_object, 'localspace', root_block, root_object.name)
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\objectsys\object_export.py", line 214, in export_node
    self.mesh_helper.export_tri_shapes(b_obj, space, parent_block, node_name)
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\objectsys\object_export.py", line 929, in export_tri_shapes
    assert((f_numverts == 3) or (f_numverts == 4)) # debug
AssertionError

location: <unknown location>:-1
```
### Console Output

```
C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\ui\shader.py:113
Traceback (most recent call last):
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\operators\nif_export_op.py", line 171, in execute
    return nif_export.NifExport(self, context).execute()
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\nif_export.py", line 261, in execute
    self.objecthelper.export_node(root_object, 'localspace', root_block, root_object.name)
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\objectsys\object_export.py", line 214, in export_n
ode
    self.mesh_helper.export_tri_shapes(b_obj, space, parent_block, node_name)
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\objectsys\object_export.py", line 929, in export_t
ri_shapes
    assert((f_numverts == 3) or (f_numverts == 4)) # debug
AssertionError

location: <unknown location>:-1

location: <unknown location>:-1
```
### Blend File

https://www.dropbox.com/s/whx77f196zjajiq/Daedric%20Steel%203.blend?dl=0
### Nif File

N/A
## Similar Known Issues

N/A
## Additional Information

N/A

**Comment by psi29a** [comment]
Please review possible fix. :)
