### ISSUE TITLE
Textures causing Blender to crash if original object removed

### ISSUE THREAD

**Issue by CorallusCaninus** [niftools/blender_nif_plugin#326]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
Trying to import a tree from Skyrim flora Overhaul isn't possible.

### Blender Nif Plugin Version Info
Nif Plugin: 2.6.0a0.dev4 22.03.2020.

### Blender Version Info
Blender 2.79b

### Platform information
Windows 10 Pro

## Context
I could import/export tree meshes with Version 2.6.0a0.dev4 30.07.2018. But trying to import the same tree only gives the node names in the Outliner.

## Steps to Reproduce
1. Import treepineforest01.nif in Blender.
2. The file is imported giving errors: last of the is access denied. (Didn't have that error with the old Plugin) 

## Expected Result
Tree is loaded completely and has all the materials applied.

## Actual Result
Nothing is imported not even the mesh itself.

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
[If relevant, include a screenshot]

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\texture\__init__.py", line 71, in create_texture_slot
    b_mat_texslot.texture = self.texture_loader.import_texture_source(image_texture.source)
AttributeError: 'str' object has no attribute 'source'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\operators\nif_import_op.py", line 156, in execute
    return nif_import.NifImport(self, context).execute()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\nif_import.py", line 136, in execute
    self.import_root(root)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\nif_import.py", line 181, in import_root
    b_obj = self.import_branch(root_block)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\nif_import.py", line 267, in import_branch
    b_child = self.import_branch(n_child, b_armature=b_armature, n_armature=n_armature)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\nif_import.py", line 220, in import_branch
    return self.objecthelper.import_geometry_object(b_armature, n_block)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\object\__init__.py", line 204, in import_geometry_object
    self.mesh.import_mesh(n_block, b_obj, transform)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\geometry\mesh\__init__.py", line 93, in import_mesh
    self.mesh_prop_processor.process_property_list(n_block, b_obj.data)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\geometry\mesh.py", line 73, in process_property_list
    self.process_props(n_block.bs_properties)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\geometry\mesh.py", line 79, in process_props
    self.process_property(prop)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\functools.py", line 745, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\shader\bsshaderproperty.py", line 117, in import_bs_lighting_shader_property
    self.texturehelper.import_bsshaderproperty_textureset(b_mat, bs_shader_property)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\texture\types\bsshadertexture.py", line 74, in import_bsshaderproperty_textureset
    self._load_glow(b_mat, textures[2])
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\texture\types\bsshadertexture.py", line 114, in _load_glow
    b_texture = self.create_texture_slot(b_mat, glow_map)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\texture\__init__.py", line 74, in create_texture_slot
    b_mat_texslot.texture = self.texture_loader.import_texture_source(image_texture)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\texture\loader.py", line 92, in import_texture_source
    fn, b_image = self.import_external_source(source)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\texture\loader.py", line 209, in import_external_source
    b_image = bpy.data.images.load(tex)
RuntimeError: Error: Cannot read 'H:\Mod Organizer Skyrim\SFO v2.81\Meshes\landscape\Trees\ ': Permission denied


location: <unknown location>:-1
```

### Console Output
```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\operators\nif_import_op.py", line 156, in execute
    return nif_import.NifImport(self, context).execute()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\nif_import.py", line 136, in execute
    self.import_root(root)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\nif_import.py", line 181, in import_root
    b_obj = self.import_branch(root_block)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\nif_import.py", line 267, in import_branch
    b_child = self.import_branch(n_child, b_armature=b_armature, n_armature=n_armature)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\nif_import.py", line 220, in import_branch
    return self.objecthelper.import_geometry_object(b_armature, n_block)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\object\__init__.py", line 204, in import_geometry_object
    self.mesh.import_mesh(n_block, b_obj, transform)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\geometry\mesh\__init__.py", line 93, in import_mesh
    self.mesh_prop_processor.process_property_list(n_block, b_obj.data)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\geometry\mesh.py", line 73, in process_property_list
    self.process_props(n_block.bs_properties)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\geometry\mesh.py", line 79, in process_props
    self.process_property(prop)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\functools.py", line 745, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\shader\bsshaderproperty.py", line 117, in import_bs_lighting_shader_property
    self.texturehelper.import_bsshaderproperty_textureset(b_mat, bs_shader_property)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\texture\types\bsshadertexture.py", line 74, in import_bsshaderproperty_textureset
    self._load_glow(b_mat, textures[2])
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\texture\types\bsshadertexture.py", line 114, in _load_glow
    b_texture = self.create_texture_slot(b_mat, glow_map)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\texture\__init__.py", line 74, in create_texture_slot
    b_mat_texslot.texture = self.texture_loader.import_texture_source(image_texture)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\texture\loader.py", line 92, in import_texture_source
    fn, b_image = self.import_external_source(source)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_nif\modules\nif_import\property\texture\loader.py", line 209, in import_external_source
    b_image = bpy.data.images.load(tex)
RuntimeError: Error: Cannot read 'H:\Mod Organizer Skyrim\SFO v2.81\Meshes\landscape\Trees\ ': Permission denied


location: <unknown location>:-1

location: <unknown location>:-1
```

### Blend File
[Attach the blend file if the issue is reproducible]

### Nif File
[Attach input or output files, samples of what the expected output should be and reproducing the issue]
[treepineforest01.nif.zip](https://github.com/niftools/blender_nif_plugin/files/4517700/treepineforest01.nif.zip)

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

**Comment by CorallusCaninus** [comment]
Hi, so I deleted all the BSLightingShaderProperties and now the Nif loads fine. It would be nice, though, to have the properties loaded like before.

**Comment by neomonkeus** [comment]
Looks to be a separate issue.
```
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/io_scene_nif/modules/nif_import/object/__init__.py", line 204, in import_geometry_object
    self.mesh.import_mesh(n_block, b_obj, transform)
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/io_scene_nif/modules/nif_import/geometry/mesh/__init__.py", line 97, in import_mesh
    bf2_index, f_map = Mesh.add_triangles_to_bmesh(b_mesh, n_triangles, v_map)
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/io_scene_nif/modules/nif_import/geometry/mesh/__init__.py", line 165, in add_triangles_to_bmesh
    for ls1 in range(0, num_unique_faces * (tri_point_list[len(ls_list)]), (tri_point_list[len(ls_list)])):
IndexError: list index out of range
```

**Comment by neomonkeus** [comment]
This imports and exports fine in 2.8, not sure it will be worth the effort to figure out what the issue is with 2.7 as the mesh code that is failing in 2.7 has been rewritten.
Recommendation is to use 2.8 release for fix as that will be best supported going forward and we will be dropping 2.7 support soon.
