### ISSUE TITLE
FONV truck collision causes export failure

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_nif_plugin#334]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
[Provide a general introduction to the issue and why it is relevant to this repository]
Unable to export the Fallout New Vegas truck successfully without error.

### Blender Nif Plugin Version Info
[Provide version information for the Blender Nif Plugin the issue occurs with, available in Blender in the Add-On section]
Blender Nif Plugin: 2.6.0.dev4.b2-79

### Blender Version Info
[Provide information on which version of Blender the issue is seen]
Version 2.79b (2.79b 2018-03-22, Blender Foundation)

### Platform information
[Provide a brief overview of what OS your running on]
MacOSX Catalina - 10.15.3 (19D76)

## Context
[Provide more detailed information to the issue itself and why it is relevant]
Unable to export the fallout new vegas truck.

## Steps to Reproduce
[Ordered list of the steps required for recreating the issue, including settings]
 #. Import the NV_truck.nif file
 #. Export the nif using "FALLOUT 3" as the game type
 #. Fails to export to a nif.

## Expected Result
[Describe what you expected to have resulted from this process]
The nif is successfully exported

## Actual Result
[Describe what you currently experience from this process, and thereby explain the bug]
It fails exporting a bhkBVMoppTreeShape collision shape, with an error related to `havok_mat`
`material.material`

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
[If relevant, include a screenshot]

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]
```
Traceback (most recent call last):
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/io_scene_nif/nif_export.py", line 185, in execute
    root_block = self.objecthelper.export_root_node(self.root_objects, filebase)
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/io_scene_nif/modules/nif_export/object/__init__.py", line 91, in export_root_node
    n_root = self.export_node(b_obj_root, None)
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/io_scene_nif/modules/nif_export/object/__init__.py", line 225, in export_node
    self.export_children(b_obj, node)
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/io_scene_nif/modules/nif_export/object/__init__.py", line 240, in export_children
    self.export_node(b_child, n_parent)
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/io_scene_nif/modules/nif_export/object/__init__.py", line 
184, in export_node
    self.export_collision(b_obj, n_parent)
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/io_scene_nif/modules/nif_export/object/__init__.py", line 260, in export_collision
    self.bhk_helper.export_collision_helper(b_obj, node)
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/io_scene_nif/modules/nif_export/collision/havok.py", line 126, in export_collision_helper
    self.export_collision_packed(b_obj, n_col_body, layer, n_havok_mat)
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/io_scene_nif/modules/nif_export/collision/havok.py", line 534, in export_collision_packed
    n_col_shape.add_shape(triangles, normals, vertices, layer, n_havok_mat)
  File "/Users/monkey/Library/Application Support/Blender/2.79/scripts/addons/pyffi/formats/nif/__init__.py", line 2997, in add_shape
    self.sub_shapes[num_shapes].material.material = material
AttributeError: 'int' object has no attribute 'material'
```

### Blend File
[Attach the blend file if the issue is reproducible]

### Nif File
[Attach input or output files, samples of what the expected output should be and reproducing the issue]
[nv_truck.nif.zip](https://github.com/niftools/blender_nif_plugin/files/4505995/nv_truck.nif.zip)

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

**Comment by neomonkeus** [comment]
The issue is caused by havok material support in pyffi, which needs to be updated and released.
