### ISSUE TITLE
Multiple Collision Export Problems

### ISSUE THREAD

**Issue by JimScript** [niftools/blender_nif_plugin#367]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
[Provide a general introduction to the issue and why it is relevant to this repository]

### Blender Nif Plugin Version Info
[Provide version information for the Blender Nif Plugin the issue occurs with, available in Blender in the Add-On section]

### Blender Version Info
[Provide information on which version of Blender the issue is seen]

### Platform information
[Provide a brief overview of what OS your running on]

## Context
[Provide more detailed information to the issue itself and why it is relevant]

## Steps to Reproduce
[Ordered list of the steps required for recreating the issue, including settings]
 #. 

## Expected Result
[Describe what you expected to have resulted from this process]

## Actual Result
[Describe what you currently experience from this process, and thereby explain the bug]

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
[If relevant, include a screenshot]

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]

### Blend File
[Attach the blend file if the issue is reproducible]

### Nif File
[Attach input or output files, samples of what the expected output should be and reproducing the issue]

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

Ok, So this is my first time using github, but this issue has been racking my mind as I found a partial solution. I was recently using the newest commit from github and tried to export a nif file with mopp collision, and it gave me an error. so I tried to look in the code to fix it, and I got a little ways by replacing * with @ at lines 524, 531, and 534 in the (io_scene_nif/modules/nif_export/collision/havok.py). But now I am getting the errors:

 

Traceback (most recent call last):
  File "C:\Users\Jim\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\operators\nif_export_op.py", line 159, in execute
    return nif_export.NifExport(self, context).execute()
  File "C:\Users\Jim\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\nif_export.py", line 172, in execute
    root_block = self.objecthelper.export_root_node(self.root_objects, filebase)
  File "C:\Users\Jim\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\object\__init__.py", line 112, in export_root_node
    n_root = self.export_node(b_obj, None)
  File "C:\Users\Jim\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\object\__init__.py", line 218, in export_node
    self.export_children(b_obj, node)
  File "C:\Users\Jim\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\object\__init__.py", line 233, in export_children
    self.export_node(b_child, n_parent)
  File "C:\Users\Jim\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\object\__init__.py", line 173, in export_node
    if self.export_collision(b_obj, n_parent):
  File "C:\Users\Jim\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\object\__init__.py", line 254, in export_collision
    self.bhk_helper.export_collision_helper(b_obj, node)
  File "C:\Users\Jim\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\collision\havok.py", line 126, in export_collision_helper
    self.export_collision_packed(b_obj, n_col_body, layer, n_havok_mat)
  File "C:\Users\Jim\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\collision\havok.py", line 539, in export_collision_packed
    n_col_shape.add_shape(triangles, normals, vertices, layer, havok_mat.material)
  File "C:\Users\Jim\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\dependencies\pyffi\formats\nif\__init__.py", line 2997, in add_shape
    self.sub_shapes[num_shapes].material.material = material
AttributeError: 'int' object has no attribute 'material'

location: <unknown location>:-1

 Weird thing is that it imports just fine, but I am not sure if I should have said this here.

**Comment by neomonkeus** [comment]
Can you fill out the sections of the template as it enable us to reproduce the issue, thanks.

**Comment by JimScript** [comment]
Again, I apologize, I am using blender 2.83 with the nif plug-in from roughly 14 days ago, and this particularly only happens when the collision is set to "mesh". Changing the lines I listed shifts the problem forward but it still does not export. Other collision types still export just fine(Well there are a few inconsistencies, but they still export). Again, I am new to this, please ask me more if you need more.

**Comment by neomonkeus** [comment]
Yeah, can you update the issue with all of the above, including providing attaching the nif in question.

**Comment by neomonkeus** [comment]
This requires some updates to PyFFI in order to resolve the underlying problem.

**Comment by Allofich** [comment]
Looks to be the same issue as https://github.com/niftools/blender_niftools_addon/issues/453.

**Comment by Allofich** [comment]
This is fixed in newer code.
